platform :ios, '7.0'

pod 'AFNetworking', '~> 1.0'
pod 'ReactiveCocoa', '1.4.0'
pod 'ViewUtils', '~> 1.1'
pod 'UIViewDrawRectBlock'
pod 'TestFlightSDK', '1.3.0.beta'
pod 'SDURLCache', '~> 1.2.0'
pod 'FlurrySDK', '~> 4.1.0'
pod 'PonyDebugger'