name: Vinylogue
options:
  bundleIdPrefix: com.twocentstudios
  deploymentTarget:
    iOS: "18.0"
  developmentLanguage: en
  xcodeVersion: "15.4"

settings:
  MARKETING_VERSION: "2.0"
  CURRENT_PROJECT_VERSION: "1"
  SWIFT_VERSION: "6.0"
  IPHONEOS_DEPLOYMENT_TARGET: "18.0"
  ENABLE_PREVIEWS: true
  GENERATE_INFOPLIST_FILE: true
  SWIFT_STRICT_CONCURRENCY: "complete"
  INFOPLIST_KEY_UIApplicationSceneManifest_Generation: true
  INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: true
  INFOPLIST_KEY_UILaunchScreen_Generation: true
  INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
  INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
  INFOPLIST_KEY_CFBundleDisplayName: "vinylogue"
  INFOPLIST_KEY_UIUserInterfaceStyle: "Light"

packages:
  Nuke:
    url: https://github.com/kean/Nuke
    majorVersion: 12.8.0
  Sharing:
    url: https://github.com/pointfreeco/swift-sharing
    majorVersion: 1.0.0
  Dependencies:
    url: https://github.com/pointfreeco/swift-dependencies
    majorVersion: 1.0.0

targets:
  Vinylogue:
    type: application
    platform: iOS
    sources:
      - path: Vinylogue
        excludes:
          - "**/CLAUDE.md"
    resources:
      - Vinylogue/Resources/Assets.xcassets
      - Vinylogue/Resources/Preview Content
      - Vinylogue/Resources/acknowledgements.md
    dependencies:
      - package: Nuke
        product: Nuke
      - package: Nuke
        product: NukeUI
      - package: Sharing
        product: Sharing
      - package: Dependencies
        product: Dependencies
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.twocentstudios.vinylogue
      DEVELOPMENT_ASSET_PATHS: "\"Vinylogue/Resources/Preview Content\""
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: YK25EF78NT
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor

  VinylogueTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: VinylogueTests
        excludes:
          - "**/CLAUDE.md"
    dependencies:
      - target: Vinylogue

  VinylogueAppStoreScreenshotUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: VinylogueAppStoreScreenshotUITests
        excludes:
          - "**/CLAUDE.md"
    dependencies:
      - target: Vinylogue

schemes:
  Vinylogue:
    build:
      targets:
        Vinylogue: all
        VinylogueTests: [test]
        VinylogueAppStoreScreenshotUITests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - VinylogueTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
  VinylogueAppStoreScreenshotUITests:
    build:
      targets:
        Vinylogue: all
        VinylogueTests: [test]
        VinylogueAppStoreScreenshotUITests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - VinylogueAppStoreScreenshotUITests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release