name: Vinylogue
options:
  bundleIdPrefix: com.twocentstudios
  deploymentTarget:
    iOS: "18.0"
  developmentLanguage: en
  xcodeVersion: "15.4"

settings:
  MARKETING_VERSION: "2.0"
  CURRENT_PROJECT_VERSION: "1"
  SWIFT_VERSION: "5.0"
  IPHONEOS_DEPLOYMENT_TARGET: "18.0"
  ENABLE_PREVIEWS: true
  GENERATE_INFOPLIST_FILE: true
  INFOPLIST_KEY_UIApplicationSceneManifest_Generation: true
  INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: true
  INFOPLIST_KEY_UILaunchScreen_Generation: true
  INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
  INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"

packages:
  Nuke:
    url: https://github.com/kean/Nuke
    majorVersion: 12.8.0

targets:
  Vinylogue:
    type: application
    platform: iOS
    sources:
      - path: Vinylogue
        excludes:
          - "**/*.md"
    resources:
      - Vinylogue/Assets.xcassets
      - Vinylogue/Preview Content
    dependencies:
      - package: Nuke
        product: Nuke
      - package: Nuke
        product: NukeUI
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.twocentstudios.vinylogue
      DEVELOPMENT_ASSET_PATHS: "\"Vinylogue/Preview Content\""
      CODE_SIGN_STYLE: Automatic
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor

schemes:
  Vinylogue:
    build:
      targets:
        Vinylogue: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release